### ISSUE TITLE
Message's Key/Value is null when message expired

### ISSUE THREAD

**Issue by mkjeff** [criteo/kafka-sharp#23]
https://github.com/criteo/kafka-sharp/blob/1ad5dbee6ad2ce33b3e022954cd9b96fec6dcd76/kafka-sharp/kafka-sharp/Protocol/Message.cs#L27

Have any chance that obtains original key/value when MessageExpired fired?

**Comment by mkjeff** [comment]
I saw the flowing lines at [ProducerRouter](https://github.com/criteo/kafka-sharp/blob/master/kafka-sharp/kafka-sharp/Routing/ProducerRouter.cs#L907-L911)
```cs
private void OnMessageExpired(ProduceMessage message)
{
      message.Message = CheckReleaseMessage(message.Message);
      MessageExpired(message.Topic, message.Message);
}
```

Can it reverse the sequence? I mean:
```cs
MessageExpired(message.Topic, message.Message);     //notify client
message.Message = CheckReleaseMessage(message.Message);    // then release message
```

Because I found we will totally lose the original message when setting **SerializeOnProduce** as true.
If this happens then the client might be able to fetch the key/value from SerializedKeyValue.

**Comment by sdanzan** [comment]
This is as expected. If you use `SerializeOnProduce=true`, original messages are lost. Reversing the sequence would imply exposing the private underlying buffer used for serialization.

**Comment by mkjeff** [comment]
I see. What about clone the message then pass into MessageExpired?

**Comment by sdanzan** [comment]
The problem is then you can memory bomb yourself in case of big broker failures, so it's not totally trivial to implement properly, and the `SerializeOnProduce` option was introduced to help you minimize garbage collection if you're not able to pool the data objects you're sending. If you absolutely need to recover your messages, you should probably be using the `false` option.

**Comment by mkjeff** [comment]
Thanks for your explanation
