### ISSUE TITLE
I can't get Message of Discarded via "IObservable<RawKafkaRecord> DiscardedMessages"

### ISSUE THREAD

**Issue by ricoisme** [criteo/kafka-sharp#24]
I tried to get message of discarded via "IObservable<RawKafkaRecord> DiscardedMessages" when client has been exception.
I always got null message on client .
is this as expected ?
my codes part as below( I am not sure if I am right)

`

producerClient.Send("Key", "Value0");//a timeout situation

  var rawKafkaRecord = producerClient.DiscardedMessages.DistinctUntilChanged()
                .Take(1).ToTask()
                .GetAwaiter().GetResult();
            rawKafkaRecord.Should().NotBeNull("rawKafkaRecord is null");//got null
            rawKafkaRecord.Key.Should().NotBeNull("Key is null");//got null
            rawKafkaRecord.Value.Should().NotBeNull("Value is null");//got null`

**Comment by ychuzevi** [comment]
Did you enable `SerializeOnProduce=true` in your configuration? If so this is expected as key/value are not kept in memory after serialization (but the rawKafkaRecord is not null).

**Comment by ricoisme** [comment]
I alwasy got rawKafkaRecord is null. but I did not enable SerializeOnProduce=true
 is there anything else i can do for that?

Thanks

**Comment by ychuzevi** [comment]
Ok. I'm not sure then, I'm unable to reproduce the issue.
Could you send a full example of the code leading to this issue? (how do you initialize the producerClient?)

`producerClient.Send("Key", "Value0");//a timeout situation` => You mean producerClient.Produce("Key", "Value0")?

**Comment by ricoisme** [comment]
Full example of the code as below 
var producerClient = new ClusterClient(config, kafkaLogger);
producerClient.Send("Key", "Value0");
var rawKafkaRecord = producerClient.DiscardedMessages.DistinctUntilChanged()
.Take(1).ToTask()
.GetAwaiter().GetResult();
rawKafkaRecord.Should().NotBeNull("rawKafkaRecord is null");
rawKafkaRecord.Key.Should().NotBeNull("Key is null");
rawKafkaRecord.Value.Should().NotBeNull("Value is null");

I configured ClientRequestTimeoutMs is 3 to make a timeout situation.
is my scenario possible to make happen message of discarded?

**Comment by ychuzevi** [comment]
Thanks. And did you check ExpiredMessages?

If you produce on a topic which does not exist for example, there won't be any timeout because there is no partition available and it will therefore be postponed until reaching its TTL. Meaning it is considered as Expired instead of Discarded by the driver.

` IObservable<RawKafkaRecord> ExpiredMessages { get; }`

**Comment by ricoisme** [comment]
As you say, I sent message to not exists partition on a topic and I can get message of expired when message reaching its TTL.
For ExpiredMessages, I have checked it and works fine.

For DiscardedMessages, I made a message overflow scenario on a topic.

note: I configured max_buffered_messages is 3 and message_ttl is 10.

my code as below
var producerClient = new ClusterClient(config, kafkaLogger);
producerClient.Send("Key", "Value0");
producerClient.Send("Key", "Value1");
producerClient.Send("Key", "Value2");
producerClient.Send("Key", "Value3");--a overflow situation
var rawKafkaRecord = producerClient.DiscardedMessages.DistinctUntilChanged()
.Take(1).ToTask()
.GetAwaiter().GetResult();
// producerClient.ObservableExpiredMessages.Subscribe(kr => _messages = kr);
// Thread.Sleep(1000 * (int.Parse(messageTtl.ToString()) + 4));// must greater than messageTtl
rawKafkaRecord.Should().NotBeNull("rawKafkaRecord is null");
rawKafkaRecord.Key.Should().NotBeNull("Key is null");
rawKafkaRecord.Value.Should().NotBeNull("Value is null");

the same as result before ,I can not get message of discarded but why ExpiredMessages event works fine.
I mean it always trigger ExpiredMessages event whatever anything  on client.
is this as expected ?

Thanks

**Comment by ychuzevi** [comment]
Yes, it is expected. You need to also modify the OverflowStrategy and set it to OverflowStrategy.Discard if you want a real overflow with the 4th message not being sent. But even so, it will be discarded synchronously so this will not trigger an event (this is for this kind of use cases that `Produce` function returns a boolean value).

Actually the driver will never trigger a Discarded event when the topic does not exist. This is because the messages are not even sent in the first place. The driver will wait for the topic to be created until the messages reach their TTL.

Discared event is for real errors during sending. So the topic needs to be defined on the cluster. You can for example try to simulate some connection issues with `MaxRetry = 0`

**Comment by ricoisme** [comment]
I see.
Thanks for your explanation.
