### ISSUE TITLE
What does the "ProcessFullMetadata: no need to refresh the routing table" mean

### ISSUE THREAD

**Issue by ricoisme** [criteo/kafka-sharp#26]
Hi

I have a question.

I found the "ProcessFullMetadata: no need to refresh the routing table" in our system log and our consumer stopped receiving records  in a few days ago.

it seems affect consumer. 

please tell me how to avoid this problem and what happened in what situation 

is there anything else i can do for that?

Thanks

Kafka:0.10.2.0
![image](https://user-images.githubusercontent.com/17023972/31582313-a0006a52-b1b2-11e7-994a-9c062449442e.png)

**Comment by sdanzan** [comment]
This is just a debug message telling that the client will avoid performing an unneeded call to the brokers to refresh the topology (typically this happens when a bunch of errors from different brokers come in a small timeframe, we avoid bombing the brokers with too many topology requests). The topology will still always be checked at least every `Configuration.RefreshMetadataInterval` whatever happens.

If your consumer stopped receiving any messages, in absence of further information I can only conclude that your consumer has nothing to read left from the brokers. You can try checking your consumer status with the `kafka-consumer-groups.sh` script provided in your kafka distribution, it is able to show you the offset lag of each partitions relatively to a given consumer group.

**Comment by ricoisme** [comment]
I tested it again on my local kafka as  below:
1.starting a new consumer group
2.starting a new producer to send 50000's message
3.my consumer have stopped receiving records after ProcessFullMetadata: no need to refresh the routing table (Configuration.RefreshMetadataInterval=5 min)
![image](https://user-images.githubusercontent.com/17023972/31626997-46a26f00-b2de-11e7-84a3-3cc24d9ba60a.png)
![image](https://user-images.githubusercontent.com/17023972/31627010-55e0da1a-b2de-11e7-96f0-114c115c9d39.png)
![image](https://user-images.githubusercontent.com/17023972/31627029-68d3df78-b2de-11e7-83c1-d7c60dbf1160.png)

AS you can see in the above image that my consumer can not receive message and display lag on each partition.

now ,producer everything works fine but I got a lot of information of debug in my system log.

is this as expect?

Thanks

**Comment by sdanzan** [comment]
Without a better view of your code I cannot really help, however I suspect you may encounter the same problem as https://github.com/criteo/kafka-sharp/issues/27, which should be corrected in the last update.

**Comment by ricoisme** [comment]
You are right.
This problem is resolved after replace kafka.dll last update.

Thanks
